name: Shell Env ";ls;"

on: pull_request

jobs:
  pull-request:
    name: Shell Env

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: test script
        env:
          CUSTOM_GITHUB_WORKFLOW: ${{ github.workflow }}
        run: |
          set -x
          set +e

          # echo $GITHUB_WORKFLOW
          # echo "$GITHUB_WORKFLOW"
          # bash -c 'printf "%q\n" "$@"' -- $GITHUB_WORKFLOW
          bash -c 'printf "%q\n" "$@"' -- "$GITHUB_WORKFLOW"

          # echo $CUSTOM_GITHUB_WORKFLOW
          # echo "$CUSTOM_GITHUB_WORKFLOW"
          # bash -c 'printf "%q\n" "$@"' -- $CUSTOM_GITHUB_WORKFLOW
          bash -c 'printf "%q\n" "$@"' -- "$CUSTOM_GITHUB_WORKFLOW"

          bash -c 'printf "%q\n" "$@"' -- '${{ github.workflow }}'
          bash -c 'printf "%q\n" "$@"' -- ${{ toJSON(github.workflow) }}

          # echo ${{ github.workflow }}
          # echo "${{ github.workflow }}"
          # bash -c 'printf "%q\n" "$@"' -- ${{ github.workflow }}
          # bash -c 'printf "%q\n" "$@"' -- "${{ github.workflow }}"
