name: Upload Artifact

on:
  pull_request:

permissions: {}

jobs:
  upload:
    name: Upload Artifact

    runs-on: ubuntu-slim

    steps:
      - name: Create zero-byte file
        run: truncate -s 0 zero.txt

      - name: Upload zero-bytes, archive=true
        uses: actions/upload-artifact@v7
        with:
          name: zero-bytes-archive-true
          path: zero.txt
          archive: true

      - name: Upload zero-bytes, archive=false
        uses: actions/upload-artifact@v7
        with:
          name: zero-bytes-archive-false
          path: zero.txt
          archive: false

      - name: Create single-byte file
        run: printf 'a' > single.txt

      - name: Upload single-byte, archive=true
        uses: actions/upload-artifact@v7
        with:
          name: single-byte-archive-true
          path: single.txt
          archive: true

      - name: Upload single-byte, archive=false
        uses: actions/upload-artifact@v7
        with:
          name: single-byte-archive-false
          path: single.txt
          archive: false
